"""post markdown support

Revision ID: 2ffd1f7942eb
Revises: 6b3fe2ac4512
Create Date: 2016-12-21 10:54:26.373288

"""

# revision identifiers, used by Alembic.
revision = '2ffd1f7942eb'
down_revision = '6b3fe2ac4512'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
