"""first use

Revision ID: 4576257d8b49
Revises: None
Create Date: 2016-12-06 20:56:23.144231

"""

# revision identifiers, used by Alembic.
revision = '4576257d8b49'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
