"""gravator

Revision ID: 4a9b389cc366
Revises: 93abb35a0de2
Create Date: 2016-12-09 14:39:14.812523

"""

# revision identifiers, used by Alembic.
revision = '4a9b389cc366'
down_revision = '93abb35a0de2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
