"""forgerypy

Revision ID: 6b3fe2ac4512
Revises: 3d0a901801fa
Create Date: 2016-12-09 17:49:44.072491

"""

# revision identifiers, used by Alembic.
revision = '6b3fe2ac4512'
down_revision = '3d0a901801fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
