"""followers

Revision ID: 7b1968f84725
Revises: 1e0a1e8fd83c
Create Date: 2016-12-22 18:26:13.527674

"""

# revision identifiers, used by Alembic.
revision = '7b1968f84725'
down_revision = '1e0a1e8fd83c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
